name: Ovidiu Zaharia
favicon: null
layout_spectrum: 0.6388296568766236
typography_spectrum: 0.07104706228710711
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.1157071425113827
  lightness: 0.9488126714713871
  saturation: 0.017751153791323304
  rhythmicContrast: 0.22090821084566414
purpose: []
